class Entities:
    bot_position = 'bot_position'
    prefix_name = 'prefix_name'
    customer_name = 'customer_name'
    shoe_id = 'shoe_id'
    shoe_model = 'shoe_model'
    shoe_name = 'shoe_name'
    shoe_size = 'shoe_size'
    shoe_color = 'shoe_color'
    color_id = 'color_id'
    coupon_code = 'coupon_code'
    coupon_id = 'coupon_id'
    shoe_category = 'shoe_category'
    shoe_quantity = 'shoe_quantity'
